package io.smarthealth.accounting.account.data;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.smarthealth.infrastructure.lang.Constants;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

/**
 *
 * @author Kelsas
 */
@Data
public class JournalData {

    public enum State {
        DRAFT,
        APPROVED,
        REVERSED
    }
    @JsonFormat(pattern = Constants.DATE_PATTERN)
    private LocalDate transactionDate = LocalDate.now();
    private String transactionId;
    private String transactionType;
    @JsonFormat(pattern = Constants.DATE_PATTERN)
    private LocalDate documentDate;
    private String activity; // financial activity accured - Department
    @Length(max = 2048)
    private String descriptions; //A description associated with this entry
    private String referenceNumber; //An additional field that is used to store additional information about the entry (Ex: chequeNo, receipt no)
    private Long paymentDetail =0L; //payment details about the transactions
    private State state=State.DRAFT; // state of transactions
    private boolean manualEntry; //Flag determines if an entry is generated by system or entered manually
    private Set<Debit> debit;
    private Set<Credit> credit;

}
