/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Kelsas
 * Created: Jul 25, 2019
 */

create table account (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), code varchar(255), name varchar(64), type varchar(255), parent_id bigint, primary key (id);) engine=InnoDB;
create table account_fiscal_year (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, active bit, end_date date, name varchar(16), start_date date, primary key (id);) engine=InnoDB;
create table account_mode_of_payment (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), name varchar(255), type varchar(255), primary key (id);) engine=InnoDB;
create table account_payment_terms (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, credit_days integer, description varchar(255), due_date_based_on varchar(255), invoice_portion double precision not null, terms_name varchar(255), primary key (id);) engine=InnoDB;
create table account_price_rule (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), title varchar(255), primary key (id);) engine=InnoDB;
create table account_transaction (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), description varchar(255), post_date date, reference varchar(255), primary key (id);) engine=InnoDB;
create table account_transaction_line (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), balance decimal(19,2), credit decimal(19,2), date_posted datetime(6), debit decimal(19,2), reconciled bit, reference varchar(255), transaction_type varchar(255), account_id bigint, period_id bigint, transaction_id bigint, primary key (id);) engine=InnoDB;;
create table addresses (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), country varchar(255), county varchar(255), billing bit, email varchar(255), fax varchar(255), line1 varchar(255), line2 varchar(255), phone varchar(255), postal_code varchar(255), title varchar(255), town varchar(255), type varchar(255), primary key (id);) engine=InnoDB;;
create table appointments (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, all_day bit, appointment_date date, end_time time, start_time time, status varchar(255), urgency varchar(255), appointment_type_id bigint, department_id bigint, patient_id bigint not null, practioneer_id bigint, procedure_id bigint, referred_by_id bigint, primary key (id);) engine=InnoDB;;
create table appointment_type (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), color varchar(255), duration integer, name varchar(255), primary key (id);) engine=InnoDB;;
create table auth_permission (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), name varchar(255), primary key (id);) engine=InnoDB;;
create table auth_permission_role (role_id bigint not null, permission_id bigint not null) engine=InnoDB;;
create table auth_role (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), name varchar(255), primary key (id);) engine=InnoDB;;
create table auth_user (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), account_expired bit, account_locked bit, credentials_expired bit, email varchar(255), enabled bit not null, name varchar(255), password varchar(255), username varchar(255), primary key (id);) engine=InnoDB;;
create table codes (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), active bit not null, code varchar(255), code_text varchar(255), code_text_short varchar(255), code_type_ct_key varchar(255), primary key (id);) engine=InnoDB;;
create table code_type (ct_key varchar(255) not null, ct_active varchar(255), ct_category varchar(255), ct_label varchar(255), primary key (ct_key)) engine=InnoDB;;
create table contacts (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), contact_role varchar(255), email varchar(255), full_name varchar(255), mobile varchar(255), telephone varchar(255), primary key (id);) engine=InnoDB;;
create table facility (id varchar(38) not null, company_id varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, code varchar(255), country varchar(255), enabled bit, name varchar(255), tax_id varchar(255), website varchar(255), credit_limit_id bigint, facility_class varchar(255), facility_type varchar(255), logo longblob, parent bit, registration_number varchar(255), primary key (id);) engine=InnoDB;;
create table facility_bed (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), create_datetime datetime(6), is_enabled bit not null, a_name varchar(255), available bit, state varchar(255), room_id bigint, primary key (id);) engine=InnoDB;;
create table facility_department (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), active bit, code varchar(255), is_store bit, dept_name varchar(255), type varchar(255), expense_account_id bigint, facility_id varchar(38), income_account_id bigint, parent_id bigint, primary key (id);) engine=InnoDB;;
create table facility_employee (employee_category varchar(255), status varchar(50), id bigint not null, department_id bigint, login_account bigint, primary key (id);) engine=InnoDB;;
create table facility_price_list (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), buying bit, currency varchar(255), enabled bit, name varchar(255), selling bit, primary key (id);) engine=InnoDB;;
create table facility_room (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), create_datetime datetime(6), is_enabled bit not null, a_name varchar(255), room_type varchar(255), ward_id bigint, primary key (id);) engine=InnoDB;;
create table facility_ward (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), create_datetime datetime(6), is_enabled bit not null, a_name varchar(255), facility_id varchar(38), primary key (id);) engine=InnoDB;;
create table organization (id varchar(38) not null, company_id varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, code varchar(255), country varchar(255), enabled bit, name varchar(255), tax_id varchar(255), website varchar(255), credit_limit_id bigint, primary key (id);) engine=InnoDB;
create table organization_address (organization_id varchar(38) not null, address_id bigint not null) engine=InnoDB;
create table organization_bank_account (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), iban varchar(255), account_name varchar(255), account_no varchar(255), bank varchar(255), branch_code varchar(255), company_account bit, default_account bit, swift_number varchar(255), gl_account_id bigint, organization_id varchar(38), primary key (id);) engine=InnoDB;
create table organization_contacts (organization_id varchar(38) not null, contact_id bigint not null) engine=InnoDB;
create table partner (id varchar(38) not null, company_id varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, code varchar(255), country varchar(255), enabled bit, name varchar(255), tax_id varchar(255), website varchar(255), credit_limit_id bigint, primary key (id);) engine=InnoDB;
create table patient (allergy_status varchar(50), blood_type varchar(15), is_alive bit not null, patient_number varchar(50), status varchar(50), id bigint not null, primary key (id);) engine=InnoDB;
create table patient_admissions (admission_type varchar(50), expected_discharge date, code varchar(255), description varchar(255), id bigint not null, admitting_doctor_id bigint, bed_id bigint, primary key (id);) engine=InnoDB;
create table patient_allergies (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, allergy varchar(255), date_recorded datetime(6), notes varchar(255), reaction varchar(255), severiity varchar(255), patient_id bigint not null, primary key (id);) engine=InnoDB;
create table patient_clinical_notes (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, date_recorded datetime(6), voided bit not null, voided_by varchar(255), voided_date datetime(6), chief_complaint varchar(255), examination_notes varchar(255), history_notes varchar(255), social_history varchar(255), health_provider_id bigint, patient_id bigint not null, visit_id bigint, primary key (id);) engine=InnoDB;
create table patient_diagnosis (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, date_recorded datetime(6), voided bit not null, voided_by varchar(255), voided_date datetime(6), certainty varchar(25), code varchar(255), description varchar(255), diagnosis_order varchar(25), health_provider_id bigint, patient_id bigint not null, visit_id bigint, primary key (id);) engine=InnoDB;
create table patient_doctor_request (order_type varchar(31) not null, id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, action varchar(255), drug bit, fulfiller_comment varchar(255), fulfiller_status varchar(255), notes varchar(255), order_datetime datetime(6), order_number varchar(255), urgency varchar(255), item_id bigint, patient_id bigint not null, requested_by_id bigint, visit_id bigint, primary key (id);) engine=InnoDB;
create table patient_identification (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), a_type varchar(255), validated bit, a_value varchar(255), patient_id bigint, primary key (id);) engine=InnoDB;
create table patient_portrait (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), content_type varchar(255), image longblob, size bigint, person_id bigint not null, primary key (id);) engine=InnoDB;
create table patient_prescriptions (as_needed bit, as_needed_condition varchar(255), brand_name varchar(255), dose double precision, dose_units varchar(255), dosing_instructions varchar(255), duration integer, duration_units varchar(255), frequency double precision, num_refills integer, quantity double precision, quantity_units varchar(255), route varchar(255), id bigint not null, primary key (id);) engine=InnoDB;
create table patient_soap_notes (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, date_recorded datetime(6), voided bit not null, voided_by varchar(255), voided_date datetime(6), assessment varchar(255), objective varchar(255), plan varchar(255), subjective varchar(255), health_provider_id bigint, patient_id bigint not null, visit_id bigint, primary key (id);) engine=InnoDB;
create table patient_visit (visit_category varchar(31) not null, id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, scheduled bit, start_datetime datetime(6), status varchar(50), stop_datetime datetime(6), visit_number varchar(38), visit_type varchar(50), patient_id bigint not null, primary key (id);) engine=InnoDB;
create table patient_vitals_record (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, date_recorded datetime(6), voided bit not null, voided_by varchar(255), voided_date datetime(6), bmi float, category varchar(255), comments varchar(255), diastolic float, height float, pulse float, respiretory float, spo2 float, systolic float, temp float, weight float, health_provider_id bigint, patient_id bigint not null, visit_id bigint, primary key (id);) engine=InnoDB;
create table payer (id varchar(38) not null, company_id varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, code varchar(255), country varchar(255), enabled bit, name varchar(255), tax_id varchar(255), website varchar(255), credit_limit_id bigint, insurance bit not null, payer_type varchar(255), debit_account_id bigint, primary key (id);) engine=InnoDB;
create table payer_scheme (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, active bit, end_date date, policy_cover varchar(255), scheme_code varchar(255), scheme_name varchar(255), start_date date, type varchar(255), payer_id varchar(38), primary key (id);) engine=InnoDB;
create table person (person_type varchar(31) not null, id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, date_of_birth date, date_registered date, gender varchar(1), given_name varchar(50), is_patient bit not null, marital_status varchar(50), middle_name varchar(50), surname varchar(50), title varchar(25), primary key (id);) engine=InnoDB;
create table person_contacts (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), email varchar(255), mobile varchar(255), telephone varchar(255), person_id bigint not null, primary key (id);) engine=InnoDB;
create table person_fingerprints (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), finger_template longblob, finger_type varchar(255), person_id bigint not null, primary key (id);) engine=InnoDB;
create table person_address (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), country varchar(255), county varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), town varchar(255), person_id bigint, primary key (id);) engine=InnoDB;
create table pricing_type (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), description varchar(255), primary key (id);) engine=InnoDB;
create table product_uom (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), active bit not null, category varchar(255), factor double precision not null, name varchar(255), rate double precision not null, rounding double precision not null, symbol varchar(10), primary key (id);) engine=InnoDB;
create table purchase_invoice (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, due_date date, invoice_amount decimal(19,2), invoice_date date, invoice_no varchar(255), is_return bit, paid bit, posting_datetime datetime(6), serial_number varchar(255), status varchar(255), transaction_date date, supplier_id varchar(38), primary key (id);) engine=InnoDB;
create table purchase_order (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, order_number varchar(255), required_date date, status varchar(255), transaction_date date, address_id bigint, contact_id bigint, price_list_id bigint, store_id bigint, supplier_id varchar(38), primary key (id);) engine=InnoDB;
create table purchase_order_item (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), amount decimal(19,2), price decimal(19,2), quantity double precision not null, item_id bigint, purchase_order_id bigint, primary key (id);) engine=InnoDB;
create table purchase_receipt (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, delivery_note varchar(255), transaction_date date, transaction_no varchar(255), receiving_store_id bigint, primary key (id);) engine=InnoDB;
create table purchase_receipt_item (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), amount decimal(19,2), discount decimal(19,2), price decimal(19,2), received_qty double precision not null, tax decimal(19,2), item_id bigint, purchase_receipt_id bigint, primary key (id);) engine=InnoDB;
create table role_user (user_id bigint not null, role_id bigint not null) engine=InnoDB;
create table stock_inventory_item (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), date_recorded datetime(6), item_type varchar(255), quantity double precision not null, serial_number varchar(255), status_type varchar(255), item_id bigint, store_id bigint, primary key (id);) engine=InnoDB;
create table stock_inventory_variance (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, comments varchar(255), date_recorded datetime(6), quantity double precision not null, item_id bigint, variance_reason bigint, store_id bigint, primary key (id);) engine=InnoDB;
create table stock_item (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), barcode varchar(255), description varchar(255), enabled bit, fixed_asset bit, item_code varchar(255), item_group varchar(255), item_name varchar(255), selling_rate decimal(19,2), shelf_life integer, uom_id bigint, primary key (id);) engine=InnoDB;
create table stock_item_price (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), enabled bit, price_list tinyblob, rate decimal(19,2), item_id bigint, primary key (id);) engine=InnoDB;
create table stock_movement (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, issuing double precision not null, move_type varchar(255), price decimal(19,2), purpose varchar(255), receiving double precision not null, reference varchar(255), total decimal(19,2), trans_datetime datetime(6), transaction_no varchar(255), item_id bigint, store_id bigint, transacting_user_id bigint, uom_id bigint, primary key (id);) engine=InnoDB;
create table stock_reorder_rule (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), reorder_level double precision not null, reorder_qty double precision not null, store tinyblob, stock_item_id bigint, primary key (id);) engine=InnoDB;
create table stock_requisition (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, requested_by varchar(255), requestion_no varchar(255), required_date date, status varchar(255), store tinyblob, terms varchar(255), transaction_date date, type varchar(255), primary key (id);) engine=InnoDB;
create table stock_requisition_item (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), quantity double precision not null, item_id bigint, requistion_id bigint, uom_id bigint, primary key (id);) engine=InnoDB;
create table stock_variance_reason (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), active bit not null, date_created datetime(6), a_name varchar(255), primary key (id);) engine=InnoDB;
create table supplier (id varchar(38) not null, company_id varchar(38), created_by varchar(255), created_on datetime(6), last_modified_by varchar(255), last_modified_on datetime(6), version bigint, code varchar(255), country varchar(255), enabled bit, name varchar(255), tax_id varchar(255), website varchar(255), credit_limit_id bigint, supplier_type varchar(255), supplier_group_id bigint, primary key (id);) engine=InnoDB;
create table supplier_group (id bigint not null auto_increment, company_id varchar(38), uuid varchar(38), description varchar(255), primary key (id);) engine=InnoDB;
alter table account drop index UK_frnp5g2qs47uu764ln1rymxur;
alter table account add constraint UK_frnp5g2qs47uu764ln1rymxur unique (uuid);
alter table account_fiscal_year drop index UK_q83pbugj718bbrihs5u72bjmv;
alter table account_fiscal_year add constraint UK_q83pbugj718bbrihs5u72bjmv unique (uuid);
alter table account_mode_of_payment drop index UK_qo7da38povv2k1p8unngtfdej;
alter table account_mode_of_payment add constraint UK_qo7da38povv2k1p8unngtfdej unique (uuid);
alter table account_payment_terms drop index UK_g4s207swbdmj9mq5rxj90f970;
alter table account_payment_terms add constraint UK_g4s207swbdmj9mq5rxj90f970 unique (uuid);
alter table account_price_rule drop index UK_1mwk8cau5autreh5dey91egmo;
alter table account_price_rule add constraint UK_1mwk8cau5autreh5dey91egmo unique (uuid);
alter table account_transaction drop index UK_lfi5qvmn5l5i514ed3e62wpsr;
alter table account_transaction add constraint UK_lfi5qvmn5l5i514ed3e62wpsr unique (uuid);
alter table account_transaction_line drop index UK_3hqm399n7bcx74wx557a8luu3;
alter table account_transaction_line add constraint UK_3hqm399n7bcx74wx557a8luu3 unique (uuid);
alter table addresses drop index UK_jrhri6bt0pf6tjfingm6q69sq;
alter table addresses add constraint UK_jrhri6bt0pf6tjfingm6q69sq unique (uuid);
alter table appointments drop index UK_acp3g017weai5e4l22eqlpt97;
alter table appointments add constraint UK_acp3g017weai5e4l22eqlpt97 unique (uuid);
alter table appointment_type drop index UK_p7s4ar75hc821n4ribmmh5ejh;
alter table appointment_type add constraint UK_p7s4ar75hc821n4ribmmh5ejh unique (uuid);
alter table auth_permission drop index UK_fl7xix4py8fibnh4whp9hioqy;
alter table auth_permission add constraint UK_fl7xix4py8fibnh4whp9hioqy unique (uuid);
alter table auth_role drop index UK_c75ddwrtfht23oqpnjwivp6cn;
alter table auth_role add constraint UK_c75ddwrtfht23oqpnjwivp6cn unique (uuid);
alter table auth_user drop index UK_preuvd4x0xcjybmclalb2rs1c;
alter table auth_user add constraint UK_preuvd4x0xcjybmclalb2rs1c unique (uuid);
alter table codes drop index UK_3ik6ey8ax2wh5p8sbdpyubgia;
alter table codes add constraint UK_3ik6ey8ax2wh5p8sbdpyubgia unique (uuid);
alter table contacts drop index UK_ksqijiw38uniybb3c9389cb6a;
alter table contacts add constraint UK_ksqijiw38uniybb3c9389cb6a unique (uuid);
alter table facility drop index UK_r2v6txjvtxgysatclx1o2iyp;
alter table facility add constraint UK_r2v6txjvtxgysatclx1o2iyp unique (id);
alter table facility_bed drop index UK_qakr06tqcb0ei5xjvy0lbnmqc;
alter table facility_bed add constraint UK_qakr06tqcb0ei5xjvy0lbnmqc unique (uuid);
alter table facility_department drop index UK_c684ht3ry56plc5nw81b0xyt4;
alter table facility_department add constraint UK_c684ht3ry56plc5nw81b0xyt4 unique (uuid);
alter table facility_price_list drop index UK_3xpe7xeidn7dc3e7xi1jjhoi;
alter table facility_price_list add constraint UK_3xpe7xeidn7dc3e7xi1jjhoi unique (uuid);
alter table facility_room drop index UK_ihq6kwfap7lrw05e2mstakqa7;
alter table facility_room add constraint UK_ihq6kwfap7lrw05e2mstakqa7 unique (uuid);
alter table facility_ward drop index UK_bkx39knym0ho6qprstbnhcne8;
alter table facility_ward add constraint UK_bkx39knym0ho6qprstbnhcne8 unique (uuid);
alter table organization_bank_account drop index UK_31fib0sf94k2q833pvy3nitqe;
alter table organization_bank_account add constraint UK_31fib0sf94k2q833pvy3nitqe unique (uuid);
alter table partner drop index UK_5irr6pnvd7h35v56tv3syaqfd;
alter table partner add constraint UK_5irr6pnvd7h35v56tv3syaqfd unique (id);
alter table patient drop index UK_b2tb8hi86ipf9i37kigakj5rb;
alter table patient add constraint UK_b2tb8hi86ipf9i37kigakj5rb unique (patient_number)
alter table patient_allergies drop index UK_599txy8k49e9ufyvd9vjn012o;
alter table patient_allergies add constraint UK_599txy8k49e9ufyvd9vjn012o unique (uuid);
alter table patient_clinical_notes drop index UK_36c6isxt9hv2xiukxnrl2nva5;
alter table patient_clinical_notes add constraint UK_36c6isxt9hv2xiukxnrl2nva5 unique (uuid);
alter table patient_diagnosis drop index UK_mbjmghrb882y3ogba6cyf1xid;
alter table patient_diagnosis add constraint UK_mbjmghrb882y3ogba6cyf1xid unique (uuid);
alter table patient_doctor_request drop index UK_8vbxa7cba1c2htah8r1fop896;
alter table patient_doctor_request add constraint UK_8vbxa7cba1c2htah8r1fop896 unique (order_number)
alter table patient_doctor_request drop index UK_gobt5svlxltesm1hpqg2shq2c;
alter table patient_doctor_request add constraint UK_gobt5svlxltesm1hpqg2shq2c unique (uuid);
alter table patient_identification drop index UK_jbwd8mrsfp25b42ejnpuq6kao;
alter table patient_identification add constraint UK_jbwd8mrsfp25b42ejnpuq6kao unique (uuid);
alter table patient_portrait drop index UK_3p1qyic2thebtljmuywufsubw;
alter table patient_portrait add constraint UK_3p1qyic2thebtljmuywufsubw unique (uuid);
alter table patient_soap_notes drop index UK_hox1dapvn08dpvlqavau0uwul;
alter table patient_soap_notes add constraint UK_hox1dapvn08dpvlqavau0uwul unique (uuid);
alter table patient_visit drop index UK_m8m9xkejimeqsu8kcxmi23bct;
alter table patient_visit add constraint UK_m8m9xkejimeqsu8kcxmi23bct unique (uuid);
alter table patient_visit drop index UK_1by07f3rrhrwe76mgdpm531mw;
alter table patient_visit add constraint UK_1by07f3rrhrwe76mgdpm531mw unique (visit_number)
alter table patient_vitals_record drop index UK_m9vv24luv1y9m10o393ns40ho;
alter table patient_vitals_record add constraint UK_m9vv24luv1y9m10o393ns40ho unique (uuid);
alter table payer drop index UK_qub310hx3drs31ayt5x92tj06;
alter table payer add constraint UK_qub310hx3drs31ayt5x92tj06 unique (id);
alter table payer_scheme drop index UK_6s7trpgelxmtbhim1e76il8l0;
alter table payer_scheme add constraint UK_6s7trpgelxmtbhim1e76il8l0 unique (uuid);
alter table person drop index UK_g9lr9owdvq776erw8111fr4l6;
alter table person add constraint UK_g9lr9owdvq776erw8111fr4l6 unique (uuid);
alter table person_contacts drop index UK_jw45cgcjs5h3sul2h0748l18n;
alter table person_contacts add constraint UK_jw45cgcjs5h3sul2h0748l18n unique (uuid);
alter table person_fingerprints drop index UK_6p15mdwsbv5vfkjthrgcm6moc;
alter table person_fingerprints add constraint UK_6p15mdwsbv5vfkjthrgcm6moc unique (uuid);
alter table person_address drop index UK_c3pw8jlje6xurhxsvvrx1srdj;
alter table person_address add constraint UK_c3pw8jlje6xurhxsvvrx1srdj unique (uuid);
alter table pricing_type drop index UK_ap7cxrl1ikqofwkwpokyatf43;
alter table pricing_type add constraint UK_ap7cxrl1ikqofwkwpokyatf43 unique (uuid);
alter table product_uom drop index UK_r50d1d2gnxgei2g17ku8vy17v;
alter table product_uom add constraint UK_r50d1d2gnxgei2g17ku8vy17v unique (uuid);
alter table purchase_invoice drop index UK_30neuvh686yv9hh8poumap3ta;
alter table purchase_invoice add constraint UK_30neuvh686yv9hh8poumap3ta unique (uuid);
alter table purchase_order drop index UK_6tj4xh4ev09bh93kq7aqay9r8;
alter table purchase_order add constraint UK_6tj4xh4ev09bh93kq7aqay9r8 unique (order_number)
alter table purchase_order drop index UK_cme43db2k2385owq7sdt8ik6l;
alter table purchase_order add constraint UK_cme43db2k2385owq7sdt8ik6l unique (uuid);
alter table purchase_order_item drop index UK_3x4oiqm6q74kkoik1249awux8;
alter table purchase_order_item add constraint UK_3x4oiqm6q74kkoik1249awux8 unique (uuid);
alter table purchase_receipt drop index UK_ib076u1l5ans11q2jf3taicb1;
alter table purchase_receipt add constraint UK_ib076u1l5ans11q2jf3taicb1 unique (uuid);
alter table purchase_receipt_item drop index UK_gqbs1rhkqkuemo0twecj31x5s;
alter table purchase_receipt_item add constraint UK_gqbs1rhkqkuemo0twecj31x5s unique (uuid);
alter table stock_inventory_item drop index UK_nrrf7pagus1qrvwjdvu9r4lnt;
alter table stock_inventory_item add constraint UK_nrrf7pagus1qrvwjdvu9r4lnt unique (uuid);
alter table stock_inventory_variance drop index UK_1g9i8jq6t4xu9i2pb4ldf3ofu;
alter table stock_inventory_variance add constraint UK_1g9i8jq6t4xu9i2pb4ldf3ofu unique (uuid);
alter table stock_item drop index UK_5wl6j3rd3gj935lr447qi8nx3;
alter table stock_item add constraint UK_5wl6j3rd3gj935lr447qi8nx3 unique (uuid);
alter table stock_item_price drop index UK_j94p6qunxx1rmup2k7e1i8qxa;
alter table stock_item_price add constraint UK_j94p6qunxx1rmup2k7e1i8qxa unique (uuid);
alter table stock_movement drop index UK_uptfto30x0qsaxgi7b005uyh;
alter table stock_movement add constraint UK_uptfto30x0qsaxgi7b005uyh unique (uuid);
alter table stock_reorder_rule drop index UK_pp4q69237itlfwd47kbjdejha;
alter table stock_reorder_rule add constraint UK_pp4q69237itlfwd47kbjdejha unique (uuid);
alter table stock_requisition drop index UK_3t8554k7jpr3lweijdprk5a14;
alter table stock_requisition add constraint UK_3t8554k7jpr3lweijdprk5a14 unique (requestion_no)
alter table stock_requisition drop index UK_av1mol7te8kphn5hye9w3i3he;
alter table stock_requisition add constraint UK_av1mol7te8kphn5hye9w3i3he unique (uuid);
alter table stock_requisition_item drop index UK_7yh3s2757du109bh8blhyqmyq;
alter table stock_requisition_item add constraint UK_7yh3s2757du109bh8blhyqmyq unique (uuid);
alter table stock_variance_reason drop index UK_mlwdp8lq8fsbcrk7p6e7mutht;
alter table stock_variance_reason add constraint UK_mlwdp8lq8fsbcrk7p6e7mutht unique (uuid);
alter table supplier drop index UK_4r9oj3rms2x3q5h2qj9huvbmu;
alter table supplier add constraint UK_4r9oj3rms2x3q5h2qj9huvbmu unique (id);
alter table supplier_group drop index UK_4lsu1hilglrodpqkye98fvp0g;
alter table supplier_group add constraint UK_4lsu1hilglrodpqkye98fvp0g unique (uuid);
alter table account add constraint FKef5lfvm7tliuagpl8wibmrqd0 foreign key (parent_id) references account (id);
alter table account_transaction_line add constraint fk_account_trx_line foreign key (account_id) references account (id);
alter table account_transaction_line add constraint fk_fiscal_year foreign key (period_id) references account_fiscal_year (id);
alter table account_transaction_line add constraint fk_trx foreign key (transaction_id) references account_transaction (id);
alter table appointments add constraint FKa97f9k89fqfs78fm6lh0cxldr foreign key (appointment_type_id) references appointment_type (id);
alter table appointments add constraint FK25fj86fvp14bcxtisp7nhca5w foreign key (department_id) references facility_department (id);
alter table appointments add constraint FKcl9b1a19a01yhjcdibna1gjl foreign key (patient_id) references patient (id);
alter table appointments add constraint FKf0dnkgrmk0h376wg00b2s6mo7 foreign key (practioneer_id) references facility_employee (id);
alter table appointments add constraint FK4uy0dyt3nlysm2i7cemp1k4j7 foreign key (procedure_id) references stock_item (id);
alter table appointments add constraint FK7qnkddvnf3cb1k6w7sxohpd7w foreign key (referred_by_id) references facility_employee (id);
alter table auth_permission_role add constraint FK5aakahneupoy14p2each26kt1 foreign key (permission_id) references auth_permission (id);
alter table auth_permission_role add constraint FK40p2bhaoyk7pqkdkxftu4005t foreign key (role_id) references auth_role (id);
alter table codes add constraint FKoj0pw9y0sie4myutfqhhsrjap foreign key (code_type_ct_key) references code_type (ct_key)
alter table facility add constraint FK_ppbu57sd1nxd1cha32biviqxs foreign key (credit_limit_id) references account_payment_terms (id);
alter table facility_bed add constraint FK4fsexf43e056n43ocr5r4ds38 foreign key (room_id) references facility_room (id);
alter table facility_department add constraint FK5wiumdlhm45fv20suwjcpy78b foreign key (expense_account_id) references account (id);
alter table facility_department add constraint FK30s49j0s3qqwa6s06a4rr6247 foreign key (facility_id) references facility (id);
alter table facility_department add constraint FKtnqqgsa2ahs89dernnllyaotq foreign key (income_account_id) references account (id);
alter table facility_department add constraint FKm4y8279c72v94vvrd6kaxqyx4 foreign key (parent_id) references facility_department (id);
alter table facility_employee add constraint FKe6fb2sit9aobtmdknq9mdfyaq foreign key (department_id) references facility_department (id);
alter table facility_employee add constraint FKbdquybqit2bm7gsd3x8pu3h9q foreign key (login_account) references auth_user (id);
alter table facility_employee add constraint FKbdpuit3ah38r8egkcbutdjb0k foreign key (id); references person (id);
alter table facility_room add constraint FKre6yh27ga80h6otdiqn0g6w4y foreign key (ward_id) references facility_ward (id);
alter table facility_ward add constraint FK9k3oeudyhbw2uo1w9lufoegky foreign key (facility_id) references facility (id);
alter table organization add constraint FKkhyk6lq9yo9mwq62cbdo2jd51 foreign key (credit_limit_id) references account_payment_terms (id);
alter table organization_address add constraint FK4mmk7jxeeymxwpwpxho8ytmy9 foreign key (address_id) references addresses (id);
alter table organization_bank_account add constraint FK6p8h672p4hc6nd01wn99xcq5g foreign key (gl_account_id) references account (id);
alter table organization_contacts add constraint FKjqueu7r9mqdxsnmqeoj3bco3o foreign key (contact_id) references contacts (id);
alter table partner add constraint FK_itocl7lul4x5hcdmbtigxkcay foreign key (credit_limit_id) references account_payment_terms (id);
alter table patient add constraint FKaxjru7sr936i3y7dy396vnon8 foreign key (id); references person (id);
alter table patient_admissions add constraint FKh9963is5wjpx8ppcf3qaxpp4e foreign key (admitting_doctor_id) references facility_employee (id);
alter table patient_admissions add constraint FK1vwg925c336el30enmsmi2riv foreign key (bed_id) references facility_bed (id);
alter table patient_admissions add constraint FKndopb9p4mdyvuqfpbshomuo02 foreign key (id); references patient_visit (id);
alter table patient_allergies add constraint FK5930n4rub3nhwfo38o85qgyjc foreign key (patient_id) references patient (id);
alter table patient_clinical_notes add constraint FKhvihhpy14rc7ut6j6l7r5f7f8 foreign key (health_provider_id) references facility_employee (id);
alter table patient_clinical_notes add constraint FKp1uysprhy62dd6ctswxx8rxgj foreign key (patient_id) references patient (id);
alter table patient_clinical_notes add constraint FKogkrbkaapa2lrvjka8q6ph9a4 foreign key (visit_id) references patient_visit (id);
alter table patient_diagnosis add constraint FKjq8dhwrqqol1ti9bq5lcuc2k4 foreign key (health_provider_id) references facility_employee (id);
alter table patient_diagnosis add constraint FK5ytynqd3ihfd996dultiy9577 foreign key (patient_id) references patient (id);
alter table patient_diagnosis add constraint FK1w820c4rxdhxgn6tpe9idahaa foreign key (visit_id) references patient_visit (id);
alter table patient_doctor_request add constraint FK3nl5rg69gobleh2c1j142ples foreign key (item_id) references stock_item (id);
alter table patient_doctor_request add constraint FKg41l2it1js44kobdxm87290tv foreign key (patient_id) references patient (id);
alter table patient_doctor_request add constraint FK7lq2cdmcktj1f5wqg1ku5g85k foreign key (requested_by_id) references facility_employee (id);
alter table patient_doctor_request add constraint FK6e05qoex58v1kxj37mt6ngm75 foreign key (visit_id) references patient_visit (id);
alter table patient_identification add constraint FKi0r48pkif4o20r30si4incxhs foreign key (patient_id) references patient (id);
alter table patient_portrait add constraint FKgldchl6hkto9cytp4ocakjsbg foreign key (person_id) references person (id);
alter table patient_prescriptions add constraint FK4gr8gkr25v8b16acf6l5mdk7e foreign key (id); references patient_doctor_request (id);
alter table patient_soap_notes add constraint FKgu91hrbsk3bg0qt29ae0oygu7 foreign key (health_provider_id) references facility_employee (id);
alter table patient_soap_notes add constraint FKery4c1ua3vlsv4qo5ko5t0674 foreign key (patient_id) references patient (id);
alter table patient_soap_notes add constraint FKkwr63p1qr8hvu937duop1j83l foreign key (visit_id) references patient_visit (id);
alter table patient_visit add constraint FKhtganuckbeasnqc150d7d3qwt foreign key (patient_id) references patient (id);
alter table patient_vitals_record add constraint FKs2kpydtcgnqq0erbinifijbb6 foreign key (health_provider_id) references facility_employee (id);
alter table patient_vitals_record add constraint FKnhnl297tpfqrqy7lfxb8w2tnl foreign key (patient_id) references patient (id);
alter table patient_vitals_record add constraint FKrio4r5s1h118wiu25qvkjdfml foreign key (visit_id) references patient_visit (id);
alter table payer add constraint FKas59u56pmvr3wtn2lpik30b8n foreign key (debit_account_id) references account (id);
alter table payer add constraint FK_2r7um484h7pqig4faxexi02mr foreign key (credit_limit_id) references account_payment_terms (id);
alter table payer_scheme add constraint FKqve8lcohvrfkn4vpdpjqqv2p3 foreign key (payer_id) references payer (id);
alter table person_contacts add constraint FK12co01nuk6fydsukv7ddf0fhl foreign key (person_id) references person (id);
alter table person_fingerprints add constraint FKphl3b0t11b2ol9h7ab7j3xen0 foreign key (person_id) references person (id);
alter table person_address add constraint FKnndfs0btabect8upo03uwgfxt foreign key (person_id) references person (id);
alter table purchase_invoice add constraint FKqtx4kjstn77n9v4wowt0mlxkx foreign key (supplier_id) references supplier (id);
alter table purchase_order add constraint FKk9jsxkksn4wfvaf1fyplgarr foreign key (address_id) references addresses (id);
alter table purchase_order add constraint FKkdobvxr1d2r9s881d9ncvoscy foreign key (contact_id) references contacts (id);
alter table purchase_order add constraint FKn6olgvva8gjadg5pfmfm4i4a6 foreign key (price_list_id) references facility_price_list (id);
alter table purchase_order add constraint FKh5h82q3ijrywwihwai3f53091 foreign key (store_id) references facility_department (id);
alter table purchase_order add constraint FK4traogu3jriq9u7e8rvm86k7i foreign key (supplier_id) references supplier (id);
alter table purchase_order_item add constraint FK8vmcavcmb26pll7emcdwv3qwo foreign key (item_id) references stock_item (id);
alter table purchase_order_item add constraint FKmj122necubadvuquvjoq967y7 foreign key (purchase_order_id) references purchase_order (id);
alter table purchase_receipt add constraint FK4rr2b5n4ejhy23lsgppuogy4r foreign key (receiving_store_id) references facility_department (id);
alter table purchase_receipt_item add constraint FKv4jrq9suk6jyquxj8j6uctj4 foreign key (item_id) references stock_item (id);
alter table purchase_receipt_item add constraint FKc6wworhljcqojwdvelwygntqv foreign key (purchase_receipt_id) references purchase_receipt (id);
alter table role_user add constraint FK55mf7c7ag4e1bt08w8uyos9og foreign key (role_id) references auth_role (id);
alter table role_user add constraint FKlb2i1httc6dlloatt4sx3u9l9 foreign key (user_id) references auth_user (id);
alter table stock_inventory_item add constraint FKrmnjh649ursdnw8vj6llws08y foreign key (item_id) references stock_item (id);
alter table stock_inventory_item add constraint FKnv8thp6lfq18nkw95dlso0cbi foreign key (store_id) references facility_department (id);
alter table stock_inventory_variance add constraint FKpwhkt4ahlf3jkulwiouxtkc2k foreign key (item_id) references stock_item (id);
alter table stock_inventory_variance add constraint FK8u8tb3h8xcwxrv6vbeplxwxcx foreign key (variance_reason) references stock_variance_reason (id);
alter table stock_inventory_variance add constraint FKbhnp5hpd5j6id2tdvhsl4sajp foreign key (store_id) references facility_department (id);
alter table stock_item add constraint FKeid250j4hs0qgu41yx4hpmt68 foreign key (uom_id) references product_uom (id);
alter table stock_item_price add constraint FKk4uh6tdp9ah8h8vplt9wmtvpy foreign key (item_id) references stock_item (id);
alter table stock_movement add constraint FKchwhrjn1qitse2ml4dre8tgcd foreign key (item_id) references stock_item (id);
alter table stock_movement add constraint FK8bwsl4gn2j9mkqx0cq03jl7rs foreign key (store_id) references facility_department (id);
alter table stock_movement add constraint FKlgnxefl1rf5udbngo8kagdyta foreign key (transacting_user_id) references facility_employee (id);
alter table stock_movement add constraint FKhxm5sdbideu6cvsrmef4u78ko foreign key (uom_id) references product_uom (id);
alter table stock_reorder_rule add constraint FKbjps8jatxchn91308ahyxq7k9 foreign key (stock_item_id) references stock_item (id);
alter table stock_requisition_item add constraint FKpntgamqvqfy54yn2ptk9ubm29 foreign key (item_id) references stock_item (id);
alter table stock_requisition_item add constraint FKmlyeevskuf3ln7t0x74pnwb5i foreign key (requistion_id) references stock_requisition (id);
alter table stock_requisition_item add constraint FKebxyy8kic257sg7n8sfnp4m7c foreign key (uom_id) references product_uom (id);
alter table supplier add constraint FKesu19c23q6lq24pou4hk02fxl foreign key (supplier_group_id) references supplier_group (id);
alter table supplier add constraint FK_m85t8ho6e4f978lggxeswcnq6 foreign key (credit_limit_id) references account_payment_terms (id);