/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.smarthealth.report.domain.enumeration;

/**
 *
 * @author Kennedy.Imbenzi
 */
public enum ReportName { 
        Trial_Balance,
        Daily_Income_Statement,
        Departmental_Payment_Report,
        Departmental_Income_Statement,
        Insurance_Statement,
        Invoice_Statement,
        Invoice,
        Doctor_Invoice,
        Supplier_Invoice,
        Patient_File ,
        Lab_Report,
        Procedure_Report,
        Request_Form,
        Prescription,
        Radiology_Report,
        Sick_Off_Note,
        Specimen_Label,
        Prescription_Label,
        Lab_Statement_Summarized,
        Lab_Statement,
        Radiology_Statement,
        Patient_List,
        Patient_Visit,
        Patient_Diagnosis,   
        Patient_Card,
        Patient_Receipt,
        Accounts,
        Income_Expense_Account,
        Chart_Of_Account,
        Balance_Sheet,
        Income_Statement,
        Petty_Cash_Form,
        Petty_Cash_statement,        
        Payment_Voucher,
        Ledger_Report,
        Journal_Report,
        Payer_Credit_Note,
        Supplier_Credit_Note,
        Goods_Receive_Note,
        Purchase_Order,
        Account_Transactions,
        Remittance_Report,
        Allocation_Report,
        Stock_Inventory,
        Stock_Adjustment,
        Referral_Form,
        Medical_Report,
        Appointment_Letter,
        Shift_Report,
        Patient_Statement,
        Dispatch_Note,
        Inventory_Stock,
        Interim_Bill,
        Expiry_Report,
        Voided_Invoice_Statement,
        Service_Statement,
        Product_Statement,
        Morbidity_Report,
        OP_Statement,
        Patient_Register,
        Dispensed_Drugs,
        Stock_Purchase_Report,
        Aging_Report,
        Supplier_Aging_Report,
        Patient_Dispensed_Drugs,
        Payment_Transactions_Statement,
        Registered_Schemes,
        Insurance_Diagnosis_Summary,
        Cashier_Shift_Statement,
        Patient_Attendance_Report
}
